import { Sparkles } from "lucide-react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { StatusChip } from "@/components/status-chip";

export function LatestRecommendationCard({
  latestRun
}: {
  latestRun: {
    finalDecision: string;
    triggerSummary: string;
    recommendation: {
      headline: string;
      rationale: string;
      proposedAction: string;
      expectedImpact: string;
      riskAssessment: string;
    } | null;
    approvalRequest: {
      title: string;
      reason: string;
    } | null;
  } | null;
}) {
  return (
    <Card className="h-full">
      <CardHeader>
        <div className="flex items-center justify-between gap-4">
          <div>
            <CardTitle>Latest recommendation</CardTitle>
            <CardDescription>The most recent operator-facing summary generated by the multi-agent workflow.</CardDescription>
          </div>
          <div className="rounded-full bg-accent/20 p-3 text-accent-foreground">
            <Sparkles className="h-5 w-5" />
          </div>
        </div>
      </CardHeader>
      <CardContent className="space-y-4">
        {latestRun?.recommendation ? (
          <>
            <div className="flex flex-wrap items-center gap-3">
              <StatusChip value={latestRun.finalDecision} />
              <p className="text-sm text-muted-foreground">{latestRun.triggerSummary}</p>
            </div>
            <div>
              <h3 className="text-2xl font-semibold">{latestRun.recommendation.headline}</h3>
              <p className="mt-2 text-sm text-muted-foreground">{latestRun.recommendation.rationale}</p>
            </div>
            <div className="grid gap-3">
              <div className="rounded-3xl bg-muted/70 p-4">
                <p className="text-xs uppercase tracking-[0.2em] text-muted-foreground">Proposed Action</p>
                <p className="mt-2 text-sm font-medium">{latestRun.recommendation.proposedAction}</p>
              </div>
              <div className="rounded-3xl bg-muted/70 p-4">
                <p className="text-xs uppercase tracking-[0.2em] text-muted-foreground">Expected Impact</p>
                <p className="mt-2 text-sm font-medium">{latestRun.recommendation.expectedImpact}</p>
              </div>
              <div className="rounded-3xl bg-muted/70 p-4">
                <p className="text-xs uppercase tracking-[0.2em] text-muted-foreground">Risk Assessment</p>
                <p className="mt-2 text-sm font-medium">{latestRun.recommendation.riskAssessment}</p>
              </div>
            </div>
            {latestRun.approvalRequest ? (
              <div className="rounded-3xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">
                <p className="font-semibold">{latestRun.approvalRequest.title}</p>
                <p className="mt-2">{latestRun.approvalRequest.reason}</p>
              </div>
            ) : null}
          </>
        ) : (
          <div className="rounded-3xl bg-muted/70 p-5 text-sm text-muted-foreground">
            No completed recommendation yet. Trigger the demo workflow to see the agents compare strategies, buy analytics, and write an audit trail.
          </div>
        )}
      </CardContent>
    </Card>
  );
}
