import Link from "next/link";
import { Sparkles } from "lucide-react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { StatusChip } from "@/components/status-chip";

export function LatestRecommendationCard({
  latestRun
}: {
  latestRun: {
    finalDecision: string;
    triggerSummary: string;
    recommendation: {
      headline: string;
      rationale: string;
      proposedAction: string;
      expectedImpact: string;
      riskAssessment: string;
    } | null;
    approvalRequest: {
      title: string;
      reason: string;
    } | null;
    executionRecords: Array<{
      status: string;
      mode: string;
      provider: string;
      amountUsd: number;
    }>;
  } | null;
}) {
  return (
    <Card className="h-full">
      <CardHeader>
        <div className="flex items-center justify-between gap-4">
          <div>
            <CardTitle>Latest recommendation</CardTitle>
            <CardDescription>The most recent operator-facing summary generated by the multi-agent workflow.</CardDescription>
          </div>
          <div className="rounded-full bg-slate-950 p-3 text-amber-300">
            <Sparkles className="h-5 w-5" />
          </div>
        </div>
      </CardHeader>
      <CardContent className="space-y-4">
        {latestRun?.recommendation ? (
          <>
            <div className="flex flex-wrap items-center gap-3">
              <StatusChip value={latestRun.finalDecision} />
              <p className="mono-ui text-xs uppercase tracking-[0.18em] text-slate-500">{latestRun.triggerSummary}</p>
            </div>
            <div>
              <h3 className="text-3xl font-semibold">{latestRun.recommendation.headline}</h3>
              <p className="mt-3 text-sm leading-7 text-slate-600">{latestRun.recommendation.rationale}</p>
            </div>
            <div className="grid gap-3 md:grid-cols-3">
              <div className="ledger-strip p-4">
                <p className="eyebrow text-slate-500">Proposed Action</p>
                <p className="mt-2 text-sm font-medium">{latestRun.recommendation.proposedAction}</p>
              </div>
              <div className="ledger-strip p-4">
                <p className="eyebrow text-slate-500">Expected Impact</p>
                <p className="mt-2 text-sm font-medium">{latestRun.recommendation.expectedImpact}</p>
              </div>
              <div className="ledger-strip p-4">
                <p className="eyebrow text-slate-500">Risk Assessment</p>
                <p className="mt-2 text-sm font-medium">{latestRun.recommendation.riskAssessment}</p>
              </div>
            </div>
            {latestRun.approvalRequest ? (
              <div className="rounded-3xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">
                <p className="font-semibold">{latestRun.approvalRequest.title}</p>
                <p className="mt-2">{latestRun.approvalRequest.reason}</p>
                <Link className="mt-3 inline-flex text-sm font-semibold text-amber-900 underline underline-offset-4" href="/runs">
                  Review and resolve in Agent runs
                </Link>
              </div>
            ) : null}
            {latestRun.executionRecords[0] ? (
              <div className="rounded-3xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-900">
                <p className="font-semibold">Execution state</p>
                <p className="mt-2">
                  {latestRun.executionRecords[0].mode.replaceAll("_", " ")} via {latestRun.executionRecords[0].provider} for {latestRun.executionRecords[0].amountUsd.toFixed(0)} USD.
                </p>
                <p className="mt-2 text-xs uppercase tracking-[0.18em] text-emerald-800/80">
                  {latestRun.executionRecords[0].status.replaceAll("_", " ")}
                </p>
              </div>
            ) : null}
          </>
        ) : (
          <div className="rounded-3xl bg-muted/70 p-5 text-sm text-muted-foreground">
            No completed recommendation yet. Trigger the demo workflow to see the agents compare strategies, buy analytics, and write an audit trail.
          </div>
        )}
      </CardContent>
    </Card>
  );
}
